# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.but0 = QtWidgets.QPushButton(self.centralwidget)
        self.but0.setGeometry(QtCore.QRect(0, 100, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.but0.setFont(font)
        self.but0.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but0.setObjectName("but0")
        self.but2 = QtWidgets.QPushButton(self.centralwidget)
        self.but2.setGeometry(QtCore.QRect(150, 100, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.but2.setFont(font)
        self.but2.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but2.setObjectName("but2")
        self.but3 = QtWidgets.QPushButton(self.centralwidget)
        self.but3.setGeometry(QtCore.QRect(225, 100, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.but3.setFont(font)
        self.but3.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but3.setObjectName("but3")
        self.but1 = QtWidgets.QPushButton(self.centralwidget)
        self.but1.setGeometry(QtCore.QRect(75, 100, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.but1.setFont(font)
        self.but1.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but1.setObjectName("but1")
        self.but2_2 = QtWidgets.QPushButton(self.centralwidget)
        self.but2_2.setGeometry(QtCore.QRect(150, 170, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.but2_2.setFont(font)
        self.but2_2.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but2_2.setObjectName("but2_2")
        self.but3_2 = QtWidgets.QPushButton(self.centralwidget)
        self.but3_2.setGeometry(QtCore.QRect(225, 170, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.but3_2.setFont(font)
        self.but3_2.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but3_2.setObjectName("but3_2")
        self.but0_2 = QtWidgets.QPushButton(self.centralwidget)
        self.but0_2.setGeometry(QtCore.QRect(0, 170, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.but0_2.setFont(font)
        self.but0_2.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but0_2.setObjectName("but0_2")
        self.but1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.but1_2.setGeometry(QtCore.QRect(75, 170, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.but1_2.setFont(font)
        self.but1_2.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but1_2.setObjectName("but1_2")
        self.but2_3 = QtWidgets.QPushButton(self.centralwidget)
        self.but2_3.setGeometry(QtCore.QRect(150, 240, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.but2_3.setFont(font)
        self.but2_3.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but2_3.setObjectName("but2_3")
        self.but1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.but1_3.setGeometry(QtCore.QRect(75, 310, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.but1_3.setFont(font)
        self.but1_3.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but1_3.setObjectName("but1_3")
        self.but3_3 = QtWidgets.QPushButton(self.centralwidget)
        self.but3_3.setGeometry(QtCore.QRect(225, 240, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.but3_3.setFont(font)
        self.but3_3.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but3_3.setObjectName("but3_3")
        self.but2_4 = QtWidgets.QPushButton(self.centralwidget)
        self.but2_4.setGeometry(QtCore.QRect(150, 310, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.but2_4.setFont(font)
        self.but2_4.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but2_4.setObjectName("but2_4")
        self.but0_3 = QtWidgets.QPushButton(self.centralwidget)
        self.but0_3.setGeometry(QtCore.QRect(0, 310, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.but0_3.setFont(font)
        self.but0_3.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but0_3.setObjectName("but0_3")
        self.but0_4 = QtWidgets.QPushButton(self.centralwidget)
        self.but0_4.setGeometry(QtCore.QRect(0, 240, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.but0_4.setFont(font)
        self.but0_4.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but0_4.setObjectName("but0_4")
        self.but3_4 = QtWidgets.QPushButton(self.centralwidget)
        self.but3_4.setGeometry(QtCore.QRect(225, 310, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.but3_4.setFont(font)
        self.but3_4.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but3_4.setObjectName("but3_4")
        self.but1_4 = QtWidgets.QPushButton(self.centralwidget)
        self.but1_4.setGeometry(QtCore.QRect(75, 240, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.but1_4.setFont(font)
        self.but1_4.setStyleSheet("background-color: rgb(70,20,40);\n"
"color: rgb(0, 170, 0);")
        self.but1_4.setObjectName("but1_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(20, 92, 100);\n"
"color: rgb(17, 108, 255);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.but3_4.clicked.connect(self.label.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.function()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.but0.setText(_translate("MainWindow", "0"))
        self.but2.setText(_translate("MainWindow", "2"))
        self.but3.setText(_translate("MainWindow", "3"))
        self.but1.setText(_translate("MainWindow", "1"))
        self.but2_2.setText(_translate("MainWindow", "6"))
        self.but3_2.setText(_translate("MainWindow", "7"))
        self.but0_2.setText(_translate("MainWindow", "4"))
        self.but1_2.setText(_translate("MainWindow", "5"))
        self.but2_3.setText(_translate("MainWindow", "+"))
        self.but1_3.setText(_translate("MainWindow", "/"))
        self.but3_3.setText(_translate("MainWindow", "-"))
        self.but2_4.setText(_translate("MainWindow", "*"))
        self.but0_3.setText(_translate("MainWindow", "="))
        self.but0_4.setText(_translate("MainWindow", "8"))
        self.but3_4.setText(_translate("MainWindow", "Delete"))
        self.but1_4.setText(_translate("MainWindow", "9"))
        self.label.setText(_translate("MainWindow", "0"))

    def function(self):
        self.but0.clicked.connect(lambda:self.writeNumber(self.but0.text()))
        self.but2.clicked.connect(lambda: self.writeNumber(self.but2.text()))
        self.but3.clicked.connect(lambda: self.writeNumber(self.but3.text()))
        self.but1.clicked.connect(lambda: self.writeNumber(self.but1.text()))
        self.but2_2.clicked.connect(lambda: self.writeNumber(self.but2_2.text()))
        self.but3_2.clicked.connect(lambda: self.writeNumber(self.but3_2.text()))
        self.but0_2.clicked.connect(lambda: self.writeNumber(self.but0_2.text()))
        self.but1_2.clicked.connect(lambda: self.writeNumber(self.but1_2.text()))
        self.but2_3.clicked.connect(lambda: self.writeNumber(self.but2_3.text()))
        self.but1_3.clicked.connect(lambda: self.writeNumber(self.but1_3.text()))
        self.but3_3.clicked.connect(lambda: self.writeNumber(self.but3_3.text()))
        self.but2_4.clicked.connect(lambda: self.writeNumber(self.but2_4.text()))
        self.but0_4.clicked.connect(lambda: self.writeNumber(self.but0_4.text()))
        self.but1_4.clicked.connect(lambda: self.writeNumber(self.but1_4.text()))

        self.but0_3.clicked.connect(self.results)




    def writeNumber(self,number):
        if(self.label.text()=="0"):
            self.label.setText(number)
        else:
            self.label.setText(self.label.text()+number)
    def results(self):
        if "/0" in self.label.text():
            self.label.setText("Error")
        else:
            res = eval(self.label.text())
            self.label.setText(str(round(res,3)))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
